//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultitableMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud_qualification
    {
        public int qualification_id { get; set; }
        public Nullable<int> roll_no { get; set; }
        public string qualification { get; set; }
    
        public virtual student student { get; set; }
    }
}
